name: Run tests, code analyzer and deploy
 
on:
  push:
    branches:
      - main

jobs:
  pipeline:
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
 
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
 
      - name: Run composer install
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate key
        run: php artisan key:generate
      
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Install front-end dependencies
        run: |
          npm install
          npm run build

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run migrations and seed to fill sqlite database
        run: php artisan migrate --seed

      - name: Run tests in Pest
        run: ./vendor/bin/pest

      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse --memory-limit=2G

      - name: Run Laravel pint
        run: ./vendor/bin/pint

      - name: Commit changes making for Laravel pint
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true
